### ISSUE TITLE
Fix shaping for Safari

### ISSUE THREAD

**Issue by davelab6** [andrestelex/sarala#2]
When I use Safari Version 7.1.6 on Mac OS X 10.9 to review http://www.impallari.com/testing/index-devanagari.php#sample_one (you need to click the 'Sample 1' tab link near the top right) then the shaping isn't working :(

**Comment by andrestelex** [comment]
I see it ok in Safari 6 and 8. Please test with new versions exported from Glyphs 2.

**Comment by andrestelex** [comment]
![captura de pantalla 2015-07-01 a las 12 12 26](https://cloud.githubusercontent.com/assets/5502786/8457932/979d5232-1fea-11e5-8ec4-aa97c3a9812e.png)

Done.

**Comment by davelab6** [comment]
Thanks!
